test:
  name: "Hospital System Performance Test"
  description: "Testing Fabric performance with patient records"
  workers:
    type: local
    number: 5

rounds:
  - label: readPatientRecord
    description: "Test reading patient records"
    txNumber: 100
    rateControl:
      type: fixed-rate
      opts:
        tps: 10
    workload:
      module: "workload/readPatient.js"

  - label: writePatientRecord
    description: "Test writing new patient records"
    txNumber: 100
    rateControl:
      type: fixed-rate
      opts:
        tps: 10
    workload:
      module: "workload/writePatient.js"
