version: "2"

services:
  caliper_2.2:
    container_name: caliper_2.2
    image: hyperledger/caliper:0.4.2
    command: launch manager --caliper-fabric-gateway-enabled
    environment:
      - CALIPER_BIND_SUT=fabric:2.2
      - CALIPER_WORKSPACE=/hyperledger/caliper/workspace
      - CALIPER_BENCHCONFIG=./benchmarkConfig.yaml
      - CALIPER_NETWORKCONFIG=./networkConfig.yaml
    volumes:
      - /home/ubuntu/thesis/blockchain/caliper-benchmark:/hyperledger/caliper/workspace
    network_mode: host
