name: "Caliper Fabric Network"
version: "2.0.0"

caliper:
  blockchain: "fabric"

channels:
  mychannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com: {}
      peer0.org2.example.com: {}

organizations:
  Org1:
    mspid: Org1MSP
    identities:
      certificates:
        - name: "Admin"
          clientPrivateKey: 
            path: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert: 
            path: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem"

    peers:
      - peer0.org1.example.com

  Org2:
    mspid: Org2MSP
    identities:
      certificates:
        - name: "Admin"
          clientPrivateKey: 
            path: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk"
          clientSignedCert: 
            path: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem"
    peers:
      - peer0.org2.example.com

orderers:
  orderer.example.com:
    url: "grpcs://localhost:7050"
    tlsCACerts:
      path: "thesis/blockchain/artifacts/channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/tls-localhost-9054-ca-orderer.pem"
peers:
  peer0.org1.example.com:
    url: "grpcs://localhost:7051"
    tlsCACerts:
      path: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem"

  peer0.org2.example.com:
    url: "grpcs://localhost:9051"
    tlsCACerts:
      path: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem"