name: "Caliper Test Network"
version: "1.0"
caliper:
  blockchain: "fabric"

channels:
  mychannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com: {}
      peer0.org2.example.com: {}

organizations:
  Org1:
    mspid: Org1MSP
    identities:
      certificates:
        - name: "Admin"
          clientPrivateKey: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/f3594fa636..._sk"
          clientSignedCert: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem"
    peers:
      - peer0.org1.example.com

  Org2:
    mspid: Org2MSP
    identities:
      certificates:
        - name: "Admin"
          clientPrivateKey: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/f3594fa636..._sk"
          clientSignedCert: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem"
    peers:
      - peer0.org2.example.com

orderers:
  orderer.example.com:
    url: "grpcs://localhost:7050"
    tlsCACerts:
      path: "thesis/blockchain/artifacts/channel/crypto-config/ordererOrganizations/orderer.example.com/tlsca/tlsca.orderer.example.com-cert.pem"

peers:
  peer0.org1.example.com:
    url: "grpcs://localhost:7051"
    tlsCACerts:
      path: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem"

  peer0.org2.example.com:
    url: "grpcs://localhost:9051"
    tlsCACerts:
      path: "thesis/blockchain/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem"
