---
name: Fabric Caliper Test Network
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true  # Set true if using TLS

channels:
  - channelName: mychannel
    contracts:
      - id: myChainCode

organizations:
  Org1:
    mspid: Org1MSP
    identities:
      certificates:
        - name: "Admin"
          clientPrivateKey:
            path: "../artifacts/channel/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../artifacts/channel/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../artifacts/channel/crypto-config/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true

  Org2:
    mspid: Org2MSP
    identities:
      certificates:
        - name: "Admin"
          clientPrivateKey:
            path: "../artifacts/channel/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../artifacts/channel/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../artifacts/channel/crypto-config/peerOrganizations/org2.example.com/connection-org2.yaml"
      discover: true

orderers:
  orderer.example.com:
    url: grpc://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com

peers:
  peer0.org1.example.com:
    url: grpc://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      request-timeout: 120000
  peer0.org2.example.com:
    url: grpc://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      request-timeout: 120000
